# Generated by Django 4.0.10 on 2025-03-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(unique=True)),
                ('status', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('memory_usage', models.FloatField(help_text='Memory usage in MB or GB')),
                ('cpu_usage', models.FloatField(help_text='CPU usage in percentage')),
            ],
        ),
    ]
